spring:
  application:
    name: AlgorithmicTradingWithClaudeCode
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  profiles:
    default: local
    group:
      local: log-local, db-local
      dev: log-dev, db-dev
      prod: log-prod, db-prod

kis:
  base-url: https://openapi.koreainvestment.com:9443
  user-id: ${KIS_ID}
  accounts:
    - name: 연금저축
      account-number: ${KIS_ACCOUNT_PENSION_NUMBER}
      app-key: ${KIS_ACCOUNT_PENSION_APP_KEY}
      app-secret: ${KIS_ACCOUNT_PENSION_APP_SECRET}
    - name: 금거래계좌
      account-number: ${KIS_ACCOUNT_GOLD_NUMBER}
      app-key: ${KIS_ACCOUNT_GOLD_APP_KEY}
      app-secret: ${KIS_ACCOUNT_GOLD_APP_SECRET}
